# Day 4 - Data Quality Assessment

## Objectives

- Detect data type issues.
- Identify invalid or out-of-range values.
- Check category consistency.
- Document all findings before data cleaning.

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/current_catalog.csv")
df1 = df.copy()

## 1. Data Type Validation

The dataset is inspected to ensure every column has the appropriate data type for analysis.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16649 entries, 0 to 16648
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   norad_id                 16649 non-null  int64
 1   name                     16649 non-null  object
 2   object_type              16647 non-null  object
 3   satellite_constellation  16649 non-null  object
 4   altitude_km              16649 non-null  float64
 5   altitude_category        16649 non-null  object
 6   orbital_band             16649 non-null  object
 7   congestion_risk          16649 non-null  object
 8   inclination              16649 non-null  float64
 9   eccentricity             16649 non-null  float64
 10  launch_year_estimate     16649 non-null  int64
 11  days_in_orbit_estimate   16649 non-null  int64
 12  orbit_lifetime_category  16649 non-null  object
 13  mean_motion              16649 non-null  float64
 14  epoch                    16649 non-null  object
 15  data_source              16649 non-null  object
 16  snapshot_date            16649 non-null  object
 17  country                  16647 non-null  object
 18  last_seen                16649 non-null  object
dtypes: float64(4), int64(3), object(12)
memory usage: 2.4+ MB

In [4]:
df1["launch_year_estimate"].head()

0    2024
1    2024
2    2024
3    2024
4    2024
Name: launch_year_estimate, dtype: int64

## 2. Invalid Value Detection

Numeric columns are checked for impossible or unrealistic values.

In [5]:
print(df1["mean_motion"].describe())

count    16649.000000
mean        14.431601
std          3.079388
min          0.073149
25%         15.027965
50%         15.275841
75%         15.343811
max         16.517224
Name: mean_motion, dtype: float64

In [6]:
df1[df1["mean_motion"] < 0]

Empty DataFrame
Columns: [norad_id, name, object_type, satellite_constellation, altitude_km, altitude_category, orbital_band, congestion_risk, inclination, eccentricity, launch_year_estimate, days_in_orbit_estimate, orbit_lifetime_category, mean_motion, epoch, data_source, snapshot_date, country, last_seen]
Index: []

In [7]:
df1["country"].value_counts(dropna=False)

country
US      12541
PRC      1475
UK        701
CIS       295
TBD       280
        ...
TMMC        1
RASC        1
STCT        1
PER         1
BOL         1
Name: count, Length: 96, dtype: int64

## 3. Category Consistency

Categorical columns are checked for inconsistent or unexpected category values.

In [8]:
df1["object_type"].value_counts(dropna=False)

object_type
PAYLOAD        16011
UNKNOWN          622
ROCKET BODY       13
NaN                2
DEBRIS             1
Name: count, dtype: int64

In [9]:
df1["altitude_category"].value_counts(dropna=False)

altitude_category
Very Low LEO    10536
Low LEO          4133
Mid LEO          1137
GEO               585
MEO               171
High LEO           44
Beyond GEO         43
Name: count, dtype: int64

In [10]:
df1["eccentricity"].describe()

count    16649.000000
mean         0.002705
std          0.039241
min          0.000003
25%          0.000117
50%          0.000166
75%          0.000324
max          0.908760
Name: eccentricity, dtype: float64

In [11]:
df1[df1["eccentricity"] < 0]

Empty DataFrame
Columns: [norad_id, name, object_type, satellite_constellation, altitude_km, altitude_category, orbital_band, congestion_risk, inclination, eccentricity, launch_year_estimate, days_in_orbit_estimate, orbit_lifetime_category, mean_motion, epoch, data_source, snapshot_date, country, last_seen]
Index: []

In [12]:
df1[df1["eccentricity"] > 1]

Empty DataFrame
Columns: [norad_id, name, object_type, satellite_constellation, altitude_km, altitude_category, orbital_band, congestion_risk, inclination, eccentricity, launch_year_estimate, days_in_orbit_estimate, orbit_lifetime_category, mean_motion, epoch, data_source, snapshot_date, country, last_seen]
Index: []

## Findings

### Data Type Assessment

- No major data type issues were observed.
- Numeric columns were stored correctly.
- `launch_year_estimate` is stored as an integer (year), which is appropriate.
- Two categorical columns (`object_type` and `country`) contain two missing values each.

### Invalid Values

- No negative values were detected in `mean_motion`.
- Country values were reviewed for consistency.
- No invalid values were detected in the inspected numeric columns.

### Category Consistency

- Categories in `object_type` and `altitude_category` were consistent.
- `eccentricity` values were within the expected range (0–1).

Overall, the dataset is suitable for the data cleaning phase.

In [13]:
df1["object_type"] = df1["object_type"].fillna("UNKNOWN")

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16649 entries, 0 to 16648
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   norad_id                 16649 non-null  int64
 1   name                     16649 non-null  object
 2   object_type              16647 non-null  object
 3   satellite_constellation  16649 non-null  object
 4   altitude_km              16649 non-null  float64
 5   altitude_category        16649 non-null  object
 6   orbital_band             16649 non-null  object
 7   congestion_risk          16649 non-null  object
 8   inclination              16649 non-null  float64
 9   eccentricity             16649 non-null  float64
 10  launch_year_estimate     16649 non-null  int64
 11  days_in_orbit_estimate   16649 non-null  int64
 12  orbit_lifetime_category  16649 non-null  object
 13  mean_motion              16649 non-null  float64
 14  epoch                    16649 non-null  object
 15  data_source              16649 non-null  object
 16  snapshot_date            16649 non-null  object
 17  country                  16647 non-null  object
 18  last_seen                16649 non-null  object
dtypes: float64(4), int64(3), object(12)
memory usage: 2.4+ MB

In [15]:
missing_values = df1.isnull().sum()

print(missing_values)

norad_id                   0
name                       0
object_type                0
satellite_constellation    0
altitude_km                0
altitude_category          0
orbital_band               0
congestion_risk            0
inclination                0
eccentricity               0
launch_year_estimate       0
days_in_orbit_estimate     0
orbit_lifetime_category    0
mean_motion                0
epoch                      0
data_source                0
snapshot_date              0
country                    2
last_seen                  0
dtype: int64

In [16]:
df1.isnull().sum()

norad_id                   0
name                       0
object_type                0
satellite_constellation    0
altitude_km                0
altitude_category          0
orbital_band               0
congestion_risk            0
inclination                0
eccentricity               0
launch_year_estimate       0
days_in_orbit_estimate     0
orbit_lifetime_category    0
mean_motion                0
epoch                      0
data_source                0
snapshot_date              0
country                    2
last_seen                  0
dtype: int64